feat: add status check job (#32)
* add status check job

* make name more descriptive

* fail purposefully

* check matrix outputs

* add filter to needs

* exit 0 to test

* remove test exit

* use failure alert approach

* fail node tests

* pass tests

* remove test code

* improve comment

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -48,3 +48,17 @@ jobs:
         working-directory: ${{ matrix.service }}
         run: |
           task test
+
+  # This job gets skipped if all upstream jobs succeeded, but it runs (and fails) if any upstream failed.
+  # This is what we want since GitHub required actions do not block merging when skipped, but can block it when failed.
+  # See: https://github.com/actions/runner/issues/2566#issuecomment-3053484216
+  run-tests-failure-alert:
+    runs-on: ubuntu-latest
+    needs: [filter, run-tests]
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    steps:
+      - name: Conditionally Fail Required Check
+        shell: bash
+        run: |
+          echo "::error Some required job has failed!"
+          exit 1
